version: "3.6"

services:
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"
  webserver:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    depends_on:
      - redis-server
    environment:
      REDISTOGO_URL: "redis://redis-server:6379/0"
      PORT: 5000
    entrypoint: ./entrypoint-webserver.sh
  worker:
    restart: always
    build: .
    volumes: 
      - .:/app
    depends_on:
      - redis-server
    environment:
      REDISTOGO_URL: "redis://redis-server:6379/0"
    entrypoint: ./entrypoint-worker.sh
